use `home-credit-default-risk`;
drop table if exists application_test;
create table application_test (
sk_id_curr varchar(6)
,name_contract_type	varchar(128)
,code_gender varchar(3)
,flag_own_car varchar(1)
,flag_own_realty varchar(1)
,cnt_children integer
,amt_income_total integer
,amt_credit integer
,amt_annuity integer
,amt_goods_price integer
,name_type_suite varchar(128)
,name_income_type varchar(128)
,name_education_type varchar(128)
,name_family_status varchar(128)
,name_housing_type varchar(128)
,region_population_relative	double 
,days_birth integer
,days_employed integer
,days_registration integer
,days_id_publish integer
,own_car_age integer
,flag_mobil integer
,flag_emp_phone integer
,flag_work_phone integer
,flag_cont_mobile integer
,flag_phone integer
,flag_email integer
,occupation_type varchar(128)
,cnt_fam_members integer
,region_rating_client integer
,region_rating_client_w_city integer
,weekday_appr_process_start varchar(128)
,hour_appr_process_start integer
,reg_region_not_live_region integer
,reg_region_not_work_region integer
,live_region_not_work_region integer
,reg_city_not_live_city integer
,reg_city_not_work_city integer
,live_city_not_work_city integer
,organization_type varchar(128)
,ext_source_1 double 
,ext_source_2 double 
,ext_source_3 double 
,apartments_avg	double 
,basementarea_avg double 
,years_beginexpluatation_avg double 
,years_build_avg double 
,commonarea_avg	double 
,elevators_avg double 
,entrances_avg double 
,floorsmax_avg double 
,floorsmin_avg double 
,landarea_avg double 
,livingapartments_avg double 
,livingarea_avg double 
,nonlivingapartments_avg double 
,nonlivingarea_avg double 
,apartments_mode double 
,basementarea_mode double 
,years_beginexpluatation_mode double 
,years_build_mode double 
,commonarea_mode double 
,elevators_mode double 
,entrances_mode double 
,floorsmax_mode double 
,floorsmin_mode double 
,landarea_mode double 
,livingapartments_mode double 
,livingarea_mode double 
,nonlivingapartments_mode double 
,nonlivingarea_mode double 
,apartments_medi double 
,basementarea_medi double 
,years_beginexpluatation_medi double 
,years_build_medi double 
,commonarea_medi double 
,elevators_medi double 
,entrances_medi double 
,floorsmax_medi double 
,floorsmin_medi double 
,landarea_medi double 
,livingapartments_medi double 
,livingarea_medi double 
,nonlivingapartments_medi double 
,nonlivingarea_medi double 
,fondkapremont_mode	varchar(128)
,housetype_mode	varchar(128)
,totalarea_mode double 
,wallsmaterial_mode	varchar(128)
,emergencystate_mode varchar(32)
,obs_30_cnt_social_circle integer
,def_30_cnt_social_circle integer
,obs_60_cnt_social_circle integer
,def_60_cnt_social_circle integer
,days_last_phone_change integer
,flag_document_2 varchar(1)
,flag_document_3 varchar(1)
,flag_document_4 varchar(1)
,flag_document_5 varchar(1)
,flag_document_6 varchar(1)
,flag_document_7 varchar(1)
,flag_document_8 varchar(1)
,flag_document_9 varchar(1)
,flag_document_10 varchar(1)
,flag_document_11 varchar(1)
,flag_document_12 varchar(1)
,flag_document_13 varchar(1)
,flag_document_14 varchar(1)
,flag_document_15 varchar(1)
,flag_document_16 varchar(1)
,flag_document_17 varchar(1)
,flag_document_18 varchar(1)
,flag_document_19 varchar(1)
,flag_document_20 varchar(1)
,flag_document_21 varchar(1)
,amt_req_credit_bureau_hour integer
,amt_req_credit_bureau_day integer
,amt_req_credit_bureau_week integer
,amt_req_credit_bureau_mon integer
,amt_req_credit_bureau_qrt integer
,amt_req_credit_bureau_year	integer
);